name: Release + Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Checkout completo (necesario para tags)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3. deps
      - name: Install dependencies
        run: npm ci

      # 4. semantic-release (source of truth)
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # 5. leer versión final desde package.json
      - name: Get version from git tag
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # 6. Deploy a Vercel
# 🚀 Deploy PROD
      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/main'
        run: |
           VITE_APP_VERSION=${{ steps.version.outputs.VERSION }} \
            npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes

# 🚀 Deploy PREVIEW
      - name: Deploy to Vercel (Preview)
        if: github.ref == 'refs/heads/develop'
        run: |
             VITE_APP_VERSION=${{ steps.version.outputs.VERSION }} \
             npx vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --yes
             
      - name: Debug version
        run: echo "VERSION=${{ steps.version.outputs.VERSION }}"